<a href="https://colab.research.google.com/github/LisMen16/ArticuloML/blob/main/NumpyIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
aux=np.array( [1,2,3,4,5])
print(aux)
print(aux.shape)

aux=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(aux.shape)
print (aux)
print(type(aux))

tpm=np.zeros((4,4))
print (tpm)

tpm=np.full((4,4),5)
print (tpm)

tpm=np.eye(4,4)
print (tpm)

tpm=np.ones((4,4))
print (tpm)

[1 2 3 4 5]
(5,)
(2, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
tpm=10*np.random.random((3,3))
print(tpm)

[[7.52945319 3.25770787 8.70972511]
 [9.8015027  6.19835937 6.58116565]
 [5.09752705 3.45333984 8.15944266]]


In [ ]:
print(tpm[:2,:2])

[[7.52945319 3.25770787]
 [9.8015027  6.19835937]]


In [ ]:
print(tpm[:2,1:3])

[[3.25770787 8.70972511]
 [6.19835937 6.58116565]]


In [ ]:
print(tpm[1,1])

6.198359371530431


In [ ]:
print(tpm[2,2])

8.159442656514754


In [ ]:
tpm=10*np.random.random((3,3))
print(tpm)

[[6.49694536 6.97793142 5.09735141]
 [3.65871936 2.75318812 7.24996278]
 [8.46294759 7.71054349 4.56151114]]


In [ ]:
mask=tpm>5
print(tpm[mask])

[6.49694536 6.97793142 5.09735141 7.24996278 8.46294759 7.71054349]


In [ ]:
mask =(tpm >= 2) & (tpm <= 4)
print(tpm[mask])

[3.65871936 2.75318812]


In [ ]:
tpm = np.random.randint(1,11,(4,4))
print(tpm)

[[ 2  3  3  3]
 [ 4 10  9  8]
 [ 3  3 10  8]
 [ 1  7  2 10]]


In [1]:
import numpy as np
# create an array with ramdon integer values batween 1 and 10
a =np.random.randint(1,11,size =(3,4))
b = np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print("adding numbers")
print(a+b)
print(np.add(a,b))
print("substracting numbers")
print (a-b)

print(np.add(a,b))
print (np.multiply(a,b))

[[8 9 8 4]
 [9 3 6 5]
 [2 2 9 3]]
[[ 7  1  4  4]
 [ 6  7 10  5]
 [ 9  7 10  9]]
(3, 4)
(3, 4)
adding numbers
[[15 10 12  8]
 [15 10 16 10]
 [11  9 19 12]]
[[15 10 12  8]
 [15 10 16 10]
 [11  9 19 12]]
substracting numbers
[[ 1  8  4  0]
 [ 3 -4 -4  0]
 [-7 -5 -1 -6]]
[[15 10 12  8]
 [15 10 16 10]
 [11  9 19 12]]
[[56  9 32 16]
 [54 21 60 25]
 [18 14 90 27]]


In [9]:
np = np.random.randint(0,100, (4,4))

np = np[np % 2 == 0]
print(np)

[66 52 48 46  8 72]


In [2]:
a =np.random.randint(1,11,size =(2,3))
b = np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[3 8 9]
 [3 2 1]]
[[ 4  3 10  3]
 [ 8  9 10  3]
 [ 4  5  4  8]]
[[112 126 146 105]
 [ 32  32  54  23]]
[[112 126 146 105]
 [ 32  32  54  23]]


In [3]:
a =np.random.randint(1,11,size =(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[5 6]
 [2 6]]
[[5 2]
 [6 6]]


In [4]:
a =np.random.randint(1,11,size =(4,3))
b=np.array ([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)

print(c.shape)
print("------------------")
print(c)

(4, 3)
(3,)
[[4 2 8]
 [5 6 1]
 [8 5 4]
 [5 8 7]]
[1 0 2]
(4, 3)
------------------
[[8 9 8]
 [4 9 3]
 [6 5 2]
 [2 9 3]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

  print(a)
  print(b)
  print(c)

  c=a+b
  print(c)

[[4 2 8]
 [5 6 1]
 [8 5 4]
 [5 8 7]]
[1 0 2]
[[ 5  2 10]
 [ 4  9  3]
 [ 6  5  2]
 [ 2  9  3]]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[4 2 8]
 [5 6 1]
 [8 5 4]
 [5 8 7]]
[1 0 2]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[4 2 8]
 [5 6 1]
 [8 5 4]
 [5 8 7]]
[1 0 2]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[4 2 8]
 [5 6 1]
 [8 5 4]
 [5 8 7]]
[1 0 2]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]
[[ 5  2 10]
 [ 6  6  3]
 [ 9  5  6]
 [ 6  8  9]]


In [6]:
a=np.array([1,2,3])

print(a)

tpm=np.tile(a,[6,1])
print(tpm)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a =np.random.randint(0,10,size =(6,6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))